---
- name: create ocp4 cluster guests
  hosts: s390x_bastion_workstation
  tasks:
  - name: create the OCP profile
    shell: /usr/local/bin/smcli pfcd -T OCPDFLT -H 172.24.26.10/44444 -U IBMAUTO -P jTghTGinJupD63yh  # noqa 204
    args:
      stdin: "{{ lookup('template', '{{ playbook_dir }}/roles/create-cluster/templates/ocpdflt.direct.j2') }}"
      executable: /bin/bash

  - name: create the bootstrap node
    include_tasks: tasks/create-guest.yml
    vars:
      coreos_role: bootstrap
      directory_entry: "{{ lookup('template', '{{ playbook_dir }}/roles/create-cluster/templates/guest.direct.j2') }}"
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: create the master nodes
    include_tasks: tasks/create-guest.yml
    vars:
      coreos_role: masters
      directory_entry: "{{ lookup('template', '{{ playbook_dir }}/roles/create-cluster/templates/guest.direct.j2') }}"
    with_items: "{{ cluster_nodes[coreos_role] }}"

  - name: create the worker nodes
    include_tasks: tasks/create-guest.yml
    vars:
      coreos_role: workers
      directory_entry: "{{ lookup('template', '{{ playbook_dir }}/roles/create-cluster/templates/guest.direct.j2') }}"
    with_items: "{{ cluster_nodes[coreos_role] }}"
    when: cluster_nodes.workers is defined
