---
- name: regenerate certificates for the new domain name
  hosts: s390x_bastion_workstation
  tasks:
  - name: generate the certificates
    include_tasks: tasks/create-certificate.yml
    with_items:
    - { filename: "cockpit", common_name: "{{ elan_host_name }}.{{ cluster_domain_name }}", subject_alt_name: ",DNS:{{ elan_host_name }}.{{ cluster_base_domain }}" }
    - { filename: "httpd", common_name: "{{ elan_host_name }}.{{ cluster_domain_name }}", subject_alt_name: ",DNS:{{ elan_host_name }}.{{ cluster_base_domain }}" }
    - { filename: "haproxy", common_name: "{{ elan_host_name }}.{{ cluster_domain_name }}", subject_alt_name: ",DNS:{{ elan_host_name }}.{{ cluster_base_domain }}" }
    - { filename: "zVM", common_name: "{{ zvm_host_name }}.{{ cluster_domain_name }}", subject_alt_name: ",DNS:{{ zvm_host_name }}.{{ cluster_base_domain }},IP:{{ zvm_ip_address }},IP:172.24.26.10" }
    - { filename: "zVMLDAP", common_name: "LDAPSRV.ibmpoc.internal", subject_alt_name: ",DNS:{{ zvm_host_name }}.{{ cluster_domain_name }},DNS:{{ zvm_host_name }}.{{ cluster_base_domain }},IP:{{ zvm_ip_address }},IP:172.24.26.10" }
    - { filename: "registry", common_name: "registry.{{ cluster_base_domain }}" }

  - name: create combined PEM file for Cockpit
    shell:
      cmd: cat certs/cockpit.cert certs/oqsCA.cert private/cockpit.pem > /etc/cockpit/ws-certs.d/cockpit-combined.cert
      chdir: /etc/pki/tls/

  - name: create combined PEM file for HAProxy
    shell:
      cmd: cat certs/haproxy.cert certs/oqsCA.cert private/haproxy.pem > /etc/haproxy/haproxy-combined.pem
      chdir: /etc/pki/tls/

  - name: create the bundle for registry
    shell:
      cmd: cat certs/registry.cert certs/oqsCA.cert private/cockpit.pem > /opt/registry/certs/registry.cert
      chdir: /etc/pki/tls

  - name: start the FTP server on z/VM # noqa no-changed-when
    shell: /usr/local/bin/smcli ia -T FTPSERVE -H 172.24.26.10/44444 -U IBMAUTO -P jTghTGinJupD63yh && sleep 2
    register: ret
    failed_when:
      - ret.rc != 0
      - '"Image already active" not in ret.stdout'

  - name: copy the PKCS#12 files to z/VM # noqa command-instead-of-module command-instead-of-shell no-changed-when
    shell:
      cmd: curl -v -T {{ item }}.p12 -Q "CWD /../VMBFS:VMSYS:GSKSSLDB/" ftp://GSKADMIN.BY.IBMAUTO:jTghTGinJupD63yh@172.24.26.10/
      chdir: /etc/pki/tls/certs
    with_items:
    - zVM
    - zVMLDAP

  - name: stop the FTP server on z/VM # noqa command-instead-of-shell no-changed-when
    shell: /usr/local/bin/smcli id -T FTPSERVE -H 172.24.26.10/44444 -U IBMAUTO -P jTghTGinJupD63yh
    when:
      - '"Image already active" not in ret.stdout'

  - name: make sure GSKADMIN can be logged on by IBMAUTO
    shell:
      cmd: |
        ldapmodify -Zx -h LDAPSRV.ibmpoc.internal -p 389 -D racfid=IBMAUTO,profiletype=user,o=ibmzvm -w 'jTghTGinJupD63yh' <<EOFLDIF
        dn: profilename=LOGONBY.GSKADMIN,profiletype=SURROGAT,o=ibmzvm
        changetype: modify
        add: racfaccesscontrol
        racfaccesscontrol: ID(IBMAUTO) ACCESS(READ) COUNT(0)

        EOFLDIF

  - name: run the certificate import task # noqa command-instead-of-shell no-changed-when
    shell:
      cmd: LDAPSRVcert.expect Y:172.24.26.10 "GSKADMIN BY IBMAUTO" jTghTGinJupD63yh
