---
# Configure the internal domain name of the cluster here.
cluster_domain_name: "{{ cluster_name }}.{{ cluster_base_domain }}"

# The IP address of the local network
# gateway, and the netmask/cidr of
# the subnet
subnet_in_addr_name: "26.24.172"

ocp_cluster_lan_name: "OCPLAN"

# This is the default node configuration.
# Please ensure the MAC addresses are
# correct for the hardware you are deploying to.
# The IP addresses must be on the same subnet as
# the cluster_subnet_prefix
# CHANGEME!
cluster_nodes:
  bootstrap:
    bootstrap-0:
      guest_name: 'OCPZBOOT'
      mac: '52:54:00:d0:f7:03'
      ip: '172.24.26.2'
      disk: "dasda"
      ign_profile: bootstrap.ign
  masters:
    master-0:
      guest_name: 'OCPZMAS0'
      mac: '52:54:00:da:70:41'
      ip: '172.24.26.3'
      disk: "dasda"
      ign_profile: master.ign
    master-1:
      guest_name: 'OCPZMAS1'
      mac: '52:54:00:a2:93:d8'
      ip: '172.24.26.4'
      disk: "dasda"
      ign_profile: master.ign
    master-2:
      guest_name: 'OCPZMAS2'
      mac: '52:54:00:d9:5b:d8'
      ip: '172.24.26.5'
      disk: "dasda"
      ign_profile: master.ign
  workers:
    worker-0:
      guest_name: 'OCPZWRK0'
      mac: '52:54:00:70:8b:74'
      ip: '172.24.26.6'
      disk: "dasda"
      ign_profile: worker.ign
    worker-1:
      guest_name: 'OCPZWRK1'
      mac: '52:54:00:70:8b:75'
      ip: '172.24.26.7'
      disk: "dasda"
      ign_profile: worker.ign
  bootworker:
    worker-2:
      guest_name: 'OCPZWRK2'
      mac: '52:54:00:70:8b:76'
      ip: '172.24.26.8'
      disk: "dasda"
      ign_profile: worker.ign
guestmemory:
  bootstrap: "16"
  masters: "16"
  workers: "16"
guestvcpus:
  bootstrap: "6"
  masters: "6"
  workers: "6"

# This will be the same as the bastion private ip when
# bastion is a separate VM, otherwise it is the gateway ip.
bastion_public_ip_address: "9.60.86.74"

ocp4_pull_secret: "{{ lookup('file', '{{ webroot }}/.secret/.ocp4_pull_secret') | from_json }}"

# If ZNETBOOT is not used, remove/comment these values
znetboot_cfg_path: "/mnt/znetboot"
znetboot_cfg_disk: "LNXMAINT 200"

# Web root for copying the Ignition files
webroot: "/var/www/html"
