---
- name: generate the certificate
  include_tasks: create-certificate.yml
  with_items:
  - { filename: "ocpApps", common_name: "*.apps.{{ cluster_name }}.{{ cluster_base_domain }}" }

- name: create combined PEM file for OCP apps
  shell:
    cmd: cat ocpApps.cert oqsCA.cert oqsRootCA.cert > ocpApps-bundle.cert
    chdir: /etc/pki/tls/certs

- name: Create OCP ConfigMap for CA certs
  command:
    cmd: oc create configmap custom-ca --from-file=ca-bundle.crt=/etc/pki/tls/certs/oqsRootCA.cert --from-file=ca.crt=/etc/pki/tls/certs/oqsCA.certs.bundle -n openshift-config

- name: Add OCP ConfigMap for CA cert
  command:
    cmd: |
      oc patch proxy/cluster --type=merge -p '{"spec":{"trustedCA":{"name":"custom-ca"}}}'

- name: Create OCP secret for the certificate and chain
  command:
    cmd: oc create secret tls oqscert --cert=/etc/pki/tls/certs/ocpApps-bundle.cert --key=/etc/pki/tls/private/ocpApps.pem -n openshift-ingress

- name: Update the Ingress Controller
  command:
    cmd: |
      oc patch ingresscontroller.operator default --type=merge -p '{"spec":{"defaultCertificate": {"name": "oqscert"}}}' -n openshift-ingress-operator

- name: Create the Custom Resource for the LDAP identity provider
  template:
    src: ldapIdentityCr.yml.j2
    dest: "~/ocp4-workdir/ldapIdentityCr.yml"

- name: Add the identity provider
  command:
    cmd: oc apply -f ~/ocp4-workdir/ldapIdentityCr.yml

- name: Set admin users as cluster-admin
  command:
    cmd: oc adm policy add-cluster-role-to-user cluster-admin {{ item }}
  loop:
    - "admin01"
    - "admin02"
    - "admin03"
    - "admin04"
    - "admin05"
